UniversityManagementSystemApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Antlr.Runtime.Tree;
using UniversityManagementSystemApp.BLL;
using UniversityManagementSystemApp.DAL.Model;

namespace UniversityManagementSystemApp.Controllers
{
    public class CourseController : Controller
    {
        CourseManager aCourseManager = new CourseManager();
        DepartmentManager aDepartmentManager = new DepartmentManager();
        SemesterManager aSemesterManager = new SemesterManager();
        TeacherManager aTeacherManager = new TeacherManager();
        AssignCourseManager assignCourseManager = new AssignCourseManager();
        ViewCourseManager aViewCourseManager = new ViewCourseManager();
        //
        // GET: /Course/
        //public ActionResult Index()
        //{
        //    return View();
        //}

        [HttpGet]
        public ActionResult AddCourse()
        {
            List<Department> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepatmentList = aDepartments;
            List<Semester> aSemesters = aSemesterManager.GetAllSemester();
            ViewBag.SemesterList = aSemesters;
            return View();
        }
        [HttpPost]
        public ActionResult AddCourse(Course aCourse)
        {
            List<Department> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepatmentList = aDepartments;
            List<Semester> aSemesters = aSemesterManager.GetAllSemester();
            ViewBag.SemesterList = aSemesters;

            string message = aCourseManager.AddCoures(aCourse);
            ViewBag.message = message;
            return View();
        }

        [HttpGet]
        public ActionResult AssignCourse()
        {
            List<Department> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepatmentList = aDepartments;
            return View();

        }

        [HttpPost]
        public ActionResult AssignCourse(AssignCourse assignCourse)
        {
            List<Department> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepatmentList = aDepartments;
            string message =assignCourseManager.SaveAssignedCourse(assignCourse);
            ViewBag.message = message;
            
            return View();
        }

        public ActionResult ViewCourse()
        {
            List<Department> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.DepatmentList = aDepartments;
            return View();
        }
       

        public JsonResult GetTeacherByDeptId(int Department_Id)
        {
            var aTeacher = aTeacherManager.GetAllTeacher();
            var teachers = aTeacher.Where(a => a.Department_Id == Department_Id).ToList();
            return Json(teachers, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetTeacherById(int Teacher_Id)
        {
            var aTeacher = aTeacherManager.GetAllTeacher();
            var ateacherslist = aTeacher.Where(a => a.Id == Teacher_Id).ToList();
            return Json(ateacherslist, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseById(int Course_Id)
        {
            var course = aCourseManager.GetAllCourse();
            var courseList = course.Where(a => a.Id == Course_Id).ToList();
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseBydeptId(int Department_Id)
        {
            var course = aCourseManager.GetAllCourse();
            var acourseList = course.Where(a => a.Department_Id == Department_Id).ToList();
            return Json(acourseList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ViewAssigendCourse(int Department_Id)
        {
            var aViewCourses = aViewCourseManager.GetAllViewCourse();
            var aViewCoursesList = aViewCourses.Where(a => a.Department_Id == Department_Id).ToList();
            return Json(aViewCoursesList, JsonRequestBehavior.AllowGet);
        }
	}
}

UniversityManagementSystemApp/Controllers/OtherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemApp.BLL;

namespace UniversityManagementSystemApp.Controllers
{
    public class OtherController : Controller
    {
        OtherManager aOtherManager = new OtherManager();
        //
        // GET: /Other/
        //public ActionResult Index()
        //{
        //    return View();
        //}

        public ActionResult UnassignCourse()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UnassignCourse(int? a)
        {
            string message = aOtherManager.UnassignCourse();
            ViewBag.message = message;
            
            return View();
        }

        public ActionResult UnAllocateClassRoom()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UnAllocateClassRoom(int? a)
        {
            string message = aOtherManager.UnAllocateClassRoom();
            ViewBag.message = message;
            return View();
        }

       
	}
}

UniversityManagementSystemApp/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemApp.BLL;
using UniversityManagementSystemApp.DAL.Model;

namespace UniversityManagementSystemApp.Controllers
{
    public class ResultController : Controller
    {
        StudentManager aStudentManager = new StudentManager();
        EnrollCourseManager aEnrollCourseManager = new EnrollCourseManager();
        ResultManager aResultManager = new ResultManager();
        ViewResultManager aViewResultManager = new ViewResultManager();
        //
        // GET: /Result/
        //public ActionResult Index()
        //{
        //    return View();
        //}

        [HttpGet]
        public ActionResult SaveStudentResult()
        {
            List<Student> aStudents = aStudentManager.GetAllStudent();

            ViewBag.StudentList = aStudents;
            List<Grade> aGrades = aResultManager.GetAllGrade();
            ViewBag.GradeList = aGrades;
            return View();
        }
        [HttpPost]
        public ActionResult SaveStudentResult(Result aResult)
        {
            List<Student> aStudents = aStudentManager.GetAllStudent();

            ViewBag.StudentList = aStudents;
            List<Grade> aGrades = aResultManager.GetAllGrade();
            ViewBag.GradeList = aGrades;
            string message = aResultManager.SaveResult(aResult);
            ViewBag.message = message;
               
            
            return View();
        }

        public ActionResult ViewResult()
        {
            List<Student> aStudents = aStudentManager.GetAllStudent();

            ViewBag.StudentList = aStudents;
            return View();
        }





        public JsonResult GetStudentById(int studentId)
        {
            var student = aStudentManager.GetAllStudent();
            var studentList = student.Where(a => a.Id == studentId).ToList();
            return Json(studentList, JsonRequestBehavior.AllowGet);

        }
        public JsonResult GetEnrollCourseByStdId(int studentIdforCourse)
        {
            var aViewEnrollCourses = aEnrollCourseManager.GetAllEnrolledCourse();
            var aViewEnrollCoursesList = aViewEnrollCourses.Where(a => a.StudentId == studentIdforCourse).ToList();
            return Json(aViewEnrollCoursesList, JsonRequestBehavior.AllowGet);

        }
        public JsonResult GetviewResultByStdId(int stdIdforECourse)
        {
            var aViewResults = aViewResultManager.GetAllEnrollCourse();
            var selectedaViewResults = aViewResults.Where(a => a.StudentId == stdIdforECourse).ToList();
            return Json(selectedaViewResults, JsonRequestBehavior.AllowGet);

        }

    }
}

UniversityManagementSystemApp/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using UniversityManagementSystemApp.BLL;
using UniversityManagementSystemApp.DAL.Model;

namespace UniversityManagementSystemApp.Controllers
{
    public class RoomController : Controller
    {
        DepartmentManager aDepartmentManager = new DepartmentManager();
        CourseManager aCourseManager = new CourseManager();
        RoomAndDayManager aRoomAndDayManager = new RoomAndDayManager();
        AllocateClassRoomManager aAllocateClassRoomManager = new AllocateClassRoomManager();
        ViewAllocatedClassRoomManager aViewAllocatedClassRoomManager = new ViewAllocatedClassRoomManager();
        //
        // GET: /Room/
        //public ActionResult Index()
        //{
        //    return View();
        //}

        [HttpGet]
        public ActionResult AllocateClassRoom()
        {
            List<Department> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.Departmentlist = aDepartments;
            List<Day> aDays = aRoomAndDayManager.GetAllDay();
            ViewBag.Daylist = aDays;
            List<Room> aRooms = aRoomAndDayManager.GetAllRoom();
            ViewBag.RoomList = aRooms;
            return View();
        }
        [HttpPost]
        public ActionResult AllocateClassRoom(AllocateClassRoom allocateClassRoom)
        {
            List<Department> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.Departmentlist = aDepartments;
            List<Day> aDays = aRoomAndDayManager.GetAllDay();
            ViewBag.Daylist = aDays;
            List<Room> aRooms = aRoomAndDayManager.GetAllRoom();
            ViewBag.RoomList = aRooms;
            string message = aAllocateClassRoomManager.SaveAlocateClassRoom(allocateClassRoom);
            ViewBag.message = message;
            return View();
        }

        public ActionResult ViewAllocatedClass()
        {
            List<Department> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.Departmentlist = aDepartments;
            return View();
        }
        public JsonResult GetCourseBydeptId(int departmentId)
        {
            var course = aCourseManager.GetAllCourse();
            var acourseList = course.Where(a => a.Department_Id == departmentId).ToList();
            return Json(acourseList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetAllocatedRoomViewByDepartmentId(int departmentId)
        {
            var aViewAllocatedClassRooms =
                aViewAllocatedClassRoomManager.GetAllViewAllocatedClassRoom();
            var seletedViewAllocatedClassRooms = aViewAllocatedClassRooms.Where(a => a.DepartmentId == departmentId).ToList();
            return Json(seletedViewAllocatedClassRooms, JsonRequestBehavior.AllowGet);
        }
       
	}
}

UniversityManagementSystemApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UMS", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>
                        <a href="#" class="dropdown-toggle dropdown-header" data-toggle="dropdown">Department<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Add Department", "AddDepartment", "Department")</li>
                            <li>@Html.ActionLink("View Department", "ViewDepartment", "Department")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle dropdown-header" data-toggle="dropdown">Course<b class="caret"></b></a>
                        <ul class="dropdown-menu ">
                            <li>@Html.ActionLink("Add Course", "AddCourse", "Course")</li>
                            <li>@Html.ActionLink("Assign Course", "AssignCourse", "Course")</li>
                            <li>@Html.ActionLink("View Course Statics", "ViewCourse", "Course")</li>


                        </ul>

                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle dropdown-header" data-toggle="dropdown">Teacher<b class="caret"></b></a>
                        <ul class="dropdown-menu ">
                            <li>@Html.ActionLink("Add Teacher", "AddTeacher", "Teacher")</li>

                        </ul>

                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle dropdown-header" data-toggle="dropdown">Student<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Register Student", "RegisterStudent", "Student")</li>
                            <li>@Html.ActionLink("Enroll Course", "EnrollStudentInCourse", "Student")</li>

                        </ul>

                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle dropdown-header" data-toggle="dropdown">Room<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Allocate Class Room", "AllocateClassRoom", "Room")</li>
                            <li>@Html.ActionLink("View Class Schedule", "ViewAllocatedClass", "Room")</li>

                        </ul>

                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle dropdown-header" data-toggle="dropdown">Result<b class="caret"></b></a>
                        <ul class="dropdown-menu ">
                            <li>@Html.ActionLink("Save Result", "SaveStudentResult", "Result")</li>
                            <li>@Html.ActionLink("View Result", "ViewResult", "Result")</li>

                        </ul>

                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle dropdown-header" data-toggle="dropdown">Other<b class="caret"></b></a>
                        <ul class="dropdown-menu ">
                            <li>@Html.ActionLink("Unassign Course", "UnassignCourse", "Other")</li>
                            <li>@Html.ActionLink("Unallocate Classroom", "UnAllocateClassRoom", "Other")</li>

                        </ul>

                    </li>


                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>