UniversityManagementSystemApp/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure.Interception;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using UniversityManagementSystemApp.BLL;
using UniversityManagementSystemApp.DAL.Model;

namespace UniversityManagementSystemApp.Controllers
{
    public class StudentController : Controller
    {
        //
        // GET: /Student/
        DepartmentManager aDepartmentManager = new DepartmentManager();
        StudentManager aStudentManager = new StudentManager();
        CourseManager aCourseManager = new CourseManager();
        EnrollCourseManager aEnrollCourseManager = new EnrollCourseManager();
        //public ActionResult Index()
        //{
        //    return View();
        //}

        [HttpGet]
        public ActionResult RegisterStudent()
        {
            List<Department> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.Departmentlist = aDepartments;
            return View();
        }
        [HttpPost]
        public ActionResult RegisterStudent(Student aStudent)
        {
            List<Department> aDepartments = aDepartmentManager.GetAllDepartment();
            ViewBag.Departmentlist = aDepartments;
            string departmentCode = aDepartmentManager.GetDepartmentCodeByID(aStudent.DepartmentId);
            aStudent.Code = departmentCode;

            string regno = departmentCode + "-";
            regno += aStudent.Date.Year.ToString();
            regno += "-";
            int regNoId = aStudentManager.GetRowCount(regno);
            //string s = (regNoId + 1).ToString("000");
            if (regNoId == 0)
            {
                regno += "00" + 1;
            }
            else
            {
                if (regNoId >= 1 && regNoId <= 9)
                {
                    int temp = regNoId + 1;
                    regno += "00" + temp;
                }
                else if (regNoId >= 10 && regNoId <= 99)
                {
                    int temp = regNoId + 1;
                    regno += "0" + temp;

                }
                else
                {
                    regno += "" + regNoId + 1;

                }


            }
            aStudent.Registration_Number = regno;



            string saveStudent = aStudentManager.SaveStudent(aStudent);
            ViewBag.message = saveStudent;
            return View();
        }

        [HttpGet]
        public ActionResult EnrollStudentInCourse()
        {
            List<Student> aStudents = aStudentManager.GetAllStudent();
            ViewBag.StudentList = aStudents;

            return View();
        }
        [HttpPost]
        public ActionResult EnrollStudentInCourse(EnrollCourse aEnrollCourse)
        {
            List<Student> aStudents = aStudentManager.GetAllStudent();

            ViewBag.StudentList = aStudents;
            int deptId = aDepartmentManager.GetDepatmentIdByCode(aEnrollCourse.Code);
            aEnrollCourse.DepartmentId = deptId;
            string message = aEnrollCourseManager.EnrollCourse(aEnrollCourse);
            ViewBag.message = message;

            return View();
        }


        public JsonResult GetStudentById(int studentId)
        {
            var student = aStudentManager.GetAllStudent();
            var studentList = student.Where(a => a.Id == studentId).ToList();
            return Json(studentList, JsonRequestBehavior.AllowGet);

        }
        public JsonResult GetCourseById(int departmentId)
        {
            var course = aCourseManager.GetAllCourse();
            var courseList = course.Where(a => a.Department_Id == departmentId).ToList();
            return Json(courseList, JsonRequestBehavior.AllowGet);

        }


    }
}

UniversityManagementSystemApp/Views/Student/EnrollStudentInCourse.cshtml
@using UniversityManagementSystemApp.DAL.Model
@model UniversityManagementSystemApp.DAL.Model.EnrollCourse

@{
    ViewBag.Title = "EnroolStudentInCourse";
    Layout = "/Views/Shared/_Layout.cshtml";
    List<Student> aStudents = ViewBag.StudentList;
}

<link href="~/Content/style.css" rel="stylesheet"/>
<style>
    label.error {
        color: red;
    }
</style>

<link href="/Content/bootstrap-datepicker3.min.css" rel="stylesheet" />

<h1>Enroll Student In a Course</h1>

<form id="enrollForm" method="POST">
    @Html.AntiForgeryToken()

    <div class="form-group" align="center">
        <table class="dataTables_sizing">
            <tr>
                <td><label for="StudentId">Student Reg. No.</label></td>
                <td>
                    <select id="StudentId" name="StudentId">
                        <option value="">Pls select a Registration name</option>
                        @foreach (Student aStudent in aStudents)
                        {
                            <option value="@aStudent.Id">@aStudent.Registration_Number</option>
                        }

                    </select>
                </td>
            </tr>
            <tr>
                <td><label for="StudentName">Name</label></td>
                <td><input type="text" class="disabled" readonly="readonly" id="StudentName" name="StudentName"/></td>
            </tr>
            <tr>
                <td><label for="StudentEmail">Email</label></td>
                <td><input type="text" class="disabled" readonly="readonly" id="StudentEmail" name="StudentEmail"/></td>
            </tr>
            <tr>
                <td><label for="Code">Department</label></td>
                <td><input id="Code" name="Code" type="text" readonly="readonly"/></td>
            </tr>
            <tr>
                <td><label for="CourseId">Select Course</label></td>
                <td>
                    <select id="CourseId" name="CourseId"></select>
                </td>
            </tr>
            <tr>
                <td><label for="EnrollDate">Date</label></td>
                <td>
                    <div class="input-group date" data-provide="datepicker">
                        <input type="text" id="EnrollDate" name="EnrollDate" class="form-control"/>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-th"></span>
                        </span>
                    </div>
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Enroll" class="btn btn-danger" />
                </td>
            </tr>
        </table>
    </div>
</form>

<div>
    @if (ViewBag.message != null)
{
    <p style="color: green">@ViewBag.message</p>
}
</div>
@section scripts
{
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>

    <script>
        
        $("#enrollForm").validate({
            rules: {
                StudentId: {
                    required: true
                },
                StudentName: { required: true },
                StudentEmail: { required: true },
                Code: { required: true },
                CourseId: { required: true },
                EnrollDate: { required: true }
            },
            messages: {
                StudentId: {
                    required: "Please select a Department"
                },
                StudentName: "",
                StudentEmail: "",
                Code: "",
                CourseId: "Please select a Course",
                EnrollDate: "Please enter a date"
            }
        });
        $(document).ready(function() {
            $("#StudentId").change(function () {
                $("#StudentName").val('');
                $("#StudentEmail").val('');
                $("#Code").val('');
                $("#CourseId").empty();
                var stdntId = $("#StudentId").val();
                var json = { studentId: stdntId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentByID", "Student")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(data) {
                        //alert(value.DepartmentId);
                        $.each(data, function(key, value) {

                            //alert(key);
                            $("#StudentName").val(value.Name);
                            $("#StudentEmail").val(value.Email);
                            $("#Code").val(value.Code);

                            var deptId = value.DepartmentId;
                            var jason = { departmentId: deptId };
                            $.ajax({
                                type: "POST",
                                url: '@Url.Action("GetCourseById", "Student")',
                                contentType: "application/json; charset=utf-8",
                                data: JSON.stringify(jason),
                                success: function (data) {
                                    $("#CourseId").append('<option value='+""+'>Pls select a Course</option>');

                                    $.each(data, function(key, value) {
                                        $("#CourseId").append('<option value=' + value.Id + '>' + value.Code + '</option>');

                                    });
                                }
                            });

                        });
                    }
                });
            });
        });
    </Script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>

        $(document).ready(function () {
            var currentDate = new Date();

                
            $('#DatePicker').datepicker({
                inline: true,
                showOtherMonths: true,
                dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                format: "dd-mm-yyyy"

            });
            $('#DatePicker').datepicker("setDate", currentDate);


           

        });


    </script>
}

UniversityManagementSystemApp/Views/Student/RegisterStudent.cshtml
@using UniversityManagementSystemApp.DAL.Model
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Department> aDepartments = ViewBag.Departmentlist;
}

<link href="/Content/style.css" rel="stylesheet" />
<style>
    label.error {
        color: red;
    }
</style>
<link href="~/Content/bootstrap-datepicker3.min.css" rel="stylesheet" />

<div>
    <div>
        <fieldset>
            <legend>Register a Student</legend>
            <form id="RegisterStudentForm" method="POST">
                <div align="center">
                    <table class="form-horizontal">
                        <tr>
                            <td><label for="Name"></label>Name</td>
                            <td><input type="text" name="Name" id="Name" /></td>
                        </tr>
                        <tr>
                            <td><label for="Email">Email</label></td>
                            <td><input type="text" name="Email" id="Email" /></td>
                        </tr>
                        <tr>
                            <td><label for="Contactno">Contact no</label></td>
                            <td><input type="text" name="Contactno" id="Contactno" /></td>
                        </tr>
                        <tr>
                            <td><label for="Date"></label>Date</td>
                            <td>
                                <div class="input-group date" data-provide="datepicker">
                                    <input type="text" id="Date" name="Date" class="form-control" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-th"></span>
                                    </span>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td><label for="Address">Address</label></td>
                            <td><textarea id="Address" name="Address" rows="3" cols="19"></textarea></td>
                        </tr>
                        <tr>
                            <td><label for="DepartmentId">Depetment</label></td>
                            <td>
                                <select name="DepartmentId" id="DepartmentId">
                                    <option value="">Pls select Your Deparment</option>
                                    @foreach (Department aDepartment in aDepartments)
                                    {
                                        <option value="@aDepartment.Id">@aDepartment.Name</option>
                                    }
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><input type="submit" name="submit" value="Register" class="btn btn-danger" /></td>
                        </tr>
                    </table>
                </div>
                <div>
                    
                        @if (ViewBag.message != null)
{
    <p style="color: green">@ViewBag.message</p>
}
                    </div>

                </form>
            </fieldset>

        </div>

    </div>
    @section scripts
    {
        <script src="~/Scripts/bootstrap-datepicker.js"></script>
        <script src="~/Scripts/jquery-1.10.2.js"></script>
        <script src="~/Scripts/jquery.validate.js"></script>
        <script>
            
            $("#RegisterStudentForm").validate({
                rules: {
                    Name: {
                        required: true
                    },
                    Email: {
                        required: true,
                        email: true
                    },
                    Contactno: {
                        required: true,
                        number: true,
                        minlength: 11
                    },
                    Address: {
                        required: true
                    },
                    DepartmentId: {
                        required: true
                    }
                },
                messages: {
                    Name: {
                        required: "Please enter Student name"
                    },
                    Email: {
                        required: "Please enter Student email",
                        email: "Please enter a valid email"
                    },
                    Contactno: {
                        required: "Please enter Student Contact number",
                        number: "Contact number must be in number format",
                        minlength: "Contact number must contain at least 11 digits"
                    },
                    Address: {
                        required: "Please enter Student address"
                    },
                    DepartmentId: {
                        required: "Please select a department"
                    }
                }
            });

            $(document).ready(function () {
                var currentDate = new Date();

                
                $('#DatePicker').datepicker({
                    inline: true,
                    showOtherMonths: true,
                    dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                    format: "dd-mm-yyyy"

                });
                $('#DatePicker').datepicker("setDate", currentDate);


           

            });

        </script>
    }